name: Build Web
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Pub get
      working-directory: ./app2
      run: flutter pub get
      shell: bash
    - name: Build
      if: ${{ github.ref == 'refs/heads/main' }}
      working-directory: ./app2
      shell: bash
      run: flutter build web
