name: Build Web
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Pub get
      working-directory: ./app2
      run: flutter pub get
      shell: bash
    - name: Build
      if: ${{ github.ref == 'refs/heads/main' }}
      working-directory: ./app2
      shell: bash
      run: flutter build web
    - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: "${{ secrets.GITHUB_TOKEN }}"
        firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
        projectId: cbeyond-f8f44
        channelId: live
        target: cbeyondadmin
        entryPoint: ./app2
