name: Build Web
jobs:
  build:
    steps:
      - name: Pub get
        working-directory: ./app1
        run: flutter pub get
      - name: Build
        if: ${{ github.ref == 'refs/heads/main' }}
        working-directory: ./app1
        run: flutter build web
